include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_build_context_synchronously: false

analyzer:
  exclude:
    - "**.g.dart"
    - "**.mocks.dart"
    - "lib/generated_plugin_registrant.dart"