// Mocks generated by Mockito 5.2.0 from annotations
// in carg/test/widgets/ad_banner_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:carg/models/player.dart' as _i5;
import 'package:carg/services/auth/auth_service.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeWidget_0 extends _i1.Fake implements _i2.Widget {
  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuth =>
      (super.noSuchMethod(Invocation.getter(#isAuth), returnValue: false)
          as bool);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i4.Future<String> googleLogIn() =>
      (super.noSuchMethod(Invocation.method(#googleLogIn, []),
          returnValue: Future<String>.value('')) as _i4.Future<String>);
  @override
  _i4.Future<void> sendSignInWithEmailLink(String? email) =>
      (super.noSuchMethod(Invocation.method(#sendSignInWithEmailLink, [email]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<String> signInWithEmailLink(String? email, String? link) => (super
      .noSuchMethod(Invocation.method(#signInWithEmailLink, [email, link]),
          returnValue: Future<String>.value('')) as _i4.Future<String>);
  @override
  _i4.Future<String> validatePhoneNumber(
          String? smsCode, String? verificationId) =>
      (super.noSuchMethod(
          Invocation.method(#validatePhoneNumber, [smsCode, verificationId]),
          returnValue: Future<String>.value('')) as _i4.Future<String>);
  @override
  _i4.Future<dynamic> changePhoneNumber(
          String? smsCode, String? verificationId) =>
      (super.noSuchMethod(
          Invocation.method(#changePhoneNumber, [smsCode, verificationId]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<dynamic> resendPhoneVerificationCode(
          String? phoneNumber, _i2.BuildContext? context) =>
      (super.noSuchMethod(
          Invocation.method(
              #resendPhoneVerificationCode, [phoneNumber, context]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<dynamic> sendPhoneVerificationCode(
          String? phoneNumber,
          _i2.BuildContext? context,
          _i3.CredentialVerificationType? credentialVerificationType) =>
      (super.noSuchMethod(
          Invocation.method(#sendPhoneVerificationCode,
              [phoneNumber, context, credentialVerificationType]),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<bool> isAlreadyLogin() =>
      (super.noSuchMethod(Invocation.method(#isAlreadyLogin, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<void> signOut(_i2.BuildContext? context) =>
      (super.noSuchMethod(Invocation.method(#signOut, [context]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> changeEmail(String? newEmail) =>
      (super.noSuchMethod(Invocation.method(#changeEmail, [newEmail]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i2.Widget getCorrectLandingScreen() =>
      (super.noSuchMethod(Invocation.method(#getCorrectLandingScreen, []),
          returnValue: _FakeWidget_0()) as _i2.Widget);
  @override
  void setCurrentPlayer(_i5.Player? player) =>
      super.noSuchMethod(Invocation.method(#setCurrentPlayer, [player]),
          returnValueForMissingStub: null);
  @override
  _i4.Future<bool> isAdFreeUser() =>
      (super.noSuchMethod(Invocation.method(#isAdFreeUser, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  void addListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
