// Mocks generated by Mockito 5.4.2 from annotations
// in carg/test/units/services/round/abstract_round_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:carg/models/carg_object.dart' as _i5;
import 'package:carg/models/score/round/round.dart' as _i2;
import 'package:carg/models/score/score.dart' as _i1;
import 'package:carg/repositories/base_repository.dart' as _i6;
import 'package:carg/repositories/score/abstract_score_repository.dart' as _i4;
import 'package:carg/services/score/abstract_score_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAbstractScoreRepository_0<T1 extends _i1.Score<_i2.Round>>
    extends _i3.SmartFake implements _i4.AbstractScoreRepository<T1> {
  _FakeAbstractScoreRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseRepository_1<T1 extends _i5.CargObject> extends _i3.SmartFake
    implements _i6.BaseRepository<T1> {
  _FakeBaseRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AbstractScoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbstractScoreService<T extends _i1.Score<_i2.Round>> extends _i3.Mock
    implements _i7.AbstractScoreService<T> {
  MockAbstractScoreService() {
    _i3.throwOnMissingStub(this);
  }

  @override
  _i4.AbstractScoreRepository<T> get scoreRepository => (super.noSuchMethod(
        Invocation.getter(#scoreRepository),
        returnValue: _FakeAbstractScoreRepository_0<T>(
          this,
          Invocation.getter(#scoreRepository),
        ),
      ) as _i4.AbstractScoreRepository<T>);

  @override
  _i6.BaseRepository<_i1.Score<_i2.Round>> get repository =>
      (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBaseRepository_1<_i1.Score<_i2.Round>>(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i6.BaseRepository<_i1.Score<_i2.Round>>);

  @override
  _i8.Future<T?> getScoreByGame(String? gameId) => (super.noSuchMethod(
        Invocation.method(
          #getScoreByGame,
          [gameId],
        ),
        returnValue: _i8.Future<T?>.value(),
      ) as _i8.Future<T?>);

  @override
  _i8.Stream<T?> getScoreByGameStream(String? gameId) => (super.noSuchMethod(
        Invocation.method(
          #getScoreByGameStream,
          [gameId],
        ),
        returnValue: _i8.Stream<T?>.empty(),
      ) as _i8.Stream<T?>);

  @override
  _i8.Future<void> deleteScoreByGame(String? gameId) => (super.noSuchMethod(
        Invocation.method(
          #deleteScoreByGame,
          [gameId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void resetLastPointedDocument() => super.noSuchMethod(
        Invocation.method(
          #resetLastPointedDocument,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i1.Score<_i2.Round>?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i8.Future<_i1.Score<_i2.Round>?>.value(),
      ) as _i8.Future<_i1.Score<_i2.Round>?>);

  @override
  _i8.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> update(_i1.Score<_i2.Round>? t) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [t],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> create(_i1.Score<_i2.Round>? t) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [t],
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
}
