default_platform(:android)

def root_path
  Dir.pwd.sub(/.*\Kfastlane/, '').sub(/.*\Kandroid/, '').sub(/.*\Kios/, '').sub(/.*\K\/\//, '')
end

before_all do |lane|
    skip_docs
end

desc "Submit to FirebaseAppDistribution"
lane :firebase do |app_id, options|
    firebase_app_distribution(
        firebase_cli_token: ENV['FIREBASE_TOKEN'],
        app: ENV['APP_ID'],
        release_notes_file: "#{root_path}/CHANGELOG.md",
        android_artifact_type: "APK",
        android_artifact_path: "#{root_path}/app-arm64-v8a-release.apk",
        groups_file: "#{root_path}/groups_file.txt",
    )
end
